#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnuplot
Version  : 5.2.7
Release  : 22
URL      : https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.7/gnuplot-5.2.7.tar.gz
Source0  : https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.7/gnuplot-5.2.7.tar.gz
Summary  : Plotting package which outputs to X11, PostScript, PNG, GIF, and others
Group    : Development/Tools
License  : gnuplot
Requires: gnuplot-bin = %{version}-%{release}
Requires: gnuplot-data = %{version}-%{release}
Requires: gnuplot-libexec = %{version}-%{release}
Requires: gnuplot-license = %{version}-%{release}
Requires: gnuplot-man = %{version}-%{release}
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : emacs
BuildRequires : emacs-x11
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(gdlib)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libturbojpeg)
BuildRequires : pkgconfig(xpm)
BuildRequires : readline-dev

%description
The Gnuplot Plotting Utility
****************************
Gnuplot is a command-line driven interactive function plotting utility
for linux, OSX, MSWin, VMS, and many other platforms.  The software is
copyrighted but freely distributed (i.e., you don't have to pay for it).
It was originally intended as graphical program to allow scientists
and students to visualize mathematical functions and data.  Gnuplot
supports many different types of terminals, plotters, and printers
(including many color devices, and pseudo-devices like LaTeX) and is
easily extensible to include new devices.

%package bin
Summary: bin components for the gnuplot package.
Group: Binaries
Requires: gnuplot-data = %{version}-%{release}
Requires: gnuplot-libexec = %{version}-%{release}
Requires: gnuplot-license = %{version}-%{release}

%description bin
bin components for the gnuplot package.


%package data
Summary: data components for the gnuplot package.
Group: Data

%description data
data components for the gnuplot package.


%package libexec
Summary: libexec components for the gnuplot package.
Group: Default
Requires: gnuplot-license = %{version}-%{release}

%description libexec
libexec components for the gnuplot package.


%package license
Summary: license components for the gnuplot package.
Group: Default

%description license
license components for the gnuplot package.


%package man
Summary: man components for the gnuplot package.
Group: Default

%description man
man components for the gnuplot package.


%prep
%setup -q -n gnuplot-5.2.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559113245
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1559113245
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnuplot
cp Copyright %{buildroot}/usr/share/package-licenses/gnuplot/Copyright
cp config/MacOSX/PkgResources/License.rtf %{buildroot}/usr/share/package-licenses/gnuplot/config_MacOSX_PkgResources_License.rtf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnuplot

%files data
%defattr(-,root,root,-)
/usr/share/gnuplot/5.2/PostScript/8859-1.ps
/usr/share/gnuplot/5.2/PostScript/8859-15.ps
/usr/share/gnuplot/5.2/PostScript/8859-2.ps
/usr/share/gnuplot/5.2/PostScript/8859-9.ps
/usr/share/gnuplot/5.2/PostScript/aglfn.txt
/usr/share/gnuplot/5.2/PostScript/cp1250.ps
/usr/share/gnuplot/5.2/PostScript/cp1251.ps
/usr/share/gnuplot/5.2/PostScript/cp1252.ps
/usr/share/gnuplot/5.2/PostScript/cp437.ps
/usr/share/gnuplot/5.2/PostScript/cp850.ps
/usr/share/gnuplot/5.2/PostScript/cp852.ps
/usr/share/gnuplot/5.2/PostScript/koi8r.ps
/usr/share/gnuplot/5.2/PostScript/koi8u.ps
/usr/share/gnuplot/5.2/PostScript/prologue.ps
/usr/share/gnuplot/5.2/PostScript/utf-8.ps
/usr/share/gnuplot/5.2/app-defaults/Gnuplot
/usr/share/gnuplot/5.2/colors_default.gp
/usr/share/gnuplot/5.2/colors_mono.gp
/usr/share/gnuplot/5.2/colors_podo.gp
/usr/share/gnuplot/5.2/gnuplot.gih
/usr/share/gnuplot/5.2/gnuplotrc
/usr/share/gnuplot/5.2/js/README
/usr/share/gnuplot/5.2/js/canvasmath.js
/usr/share/gnuplot/5.2/js/canvastext.js
/usr/share/gnuplot/5.2/js/gnuplot_common.js
/usr/share/gnuplot/5.2/js/gnuplot_dashedlines.js
/usr/share/gnuplot/5.2/js/gnuplot_mouse.css
/usr/share/gnuplot/5.2/js/gnuplot_mouse.js
/usr/share/gnuplot/5.2/js/gnuplot_svg.js
/usr/share/gnuplot/5.2/js/grid.png
/usr/share/gnuplot/5.2/js/help.png
/usr/share/gnuplot/5.2/js/nextzoom.png
/usr/share/gnuplot/5.2/js/previouszoom.png
/usr/share/gnuplot/5.2/js/return.png
/usr/share/gnuplot/5.2/js/textzoom.png
/usr/share/gnuplot/5.2/lua/gnuplot-tikz.lua
/usr/share/gnuplot/5.2/qt/qtgnuplot_fr.qm
/usr/share/gnuplot/5.2/qt/qtgnuplot_ja.qm

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gnuplot/5.2/gnuplot_qt
/usr/libexec/gnuplot/5.2/gnuplot_x11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnuplot/Copyright
/usr/share/package-licenses/gnuplot/config_MacOSX_PkgResources_License.rtf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnuplot-ja.1
/usr/share/man/man1/gnuplot.1
